# Site settings
author: Kareem Rolle
title: “Why did you decide to study Software Engineering?”
header-img: img/home-bg.png
email: kareemrolle@yahoo.com
copyright_name: Kareem Rolle
description: > # this means to ignore newlines until "baseurl:"
  My tech journey...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kareemallah

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
